### ISSUE TITLE
🚩 ROADMAP

### ISSUE THREAD

**Issue by Gorzas** [Gorzas/gorzas.github.io#8]
**v0.0.1**
- [x] read Tiago Forte's Second Brain emails
  - [x] seek cheatsheet for Second brain (or create one)
- [x] make markdowns browseable
- [x] add own theme for markdowns
  - [x] https://github.com/maximevaillancourt/digital-garden-jekyll-template/tree/main

**v0.0.2**
- [ ] add categories, tags and types
- [x] set jdcano.com domain

**v1.0.0** (clear MVP)
- [ ] customize CSS

**v2.0.0** (ideas)
- [ ] Release Second Brain with a complete website:
  - [ ] blog
  - [ ] About me
  - [ ] projects
  - [ ] split into categories: music, writing and tech

**Comment by Gorzas** [comment]
Patch, minor and major versions aren't strictly necessary in a Digital Garden, but I rather use it to organize work and see visual progress.
